language: scala
scala:
- 2.12.4
sudo: false
script:
- sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
- sbt coveralls
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
env:
  secure: T777hAhyhqOIDuEsYWNFlGfZXODYCQAIIRa8o9A4S1G0LMvOSf+wG5adsqZAyGO6GURBnkz9lYIf8O3q97EpTXPhGKgBz4Ge1dlYxIbPYh/gi6qslmSzzgiXE+9KWKKcvA+bteQ0AQbu5FNYXgLSWNhiqVNVjiRJsPr9XzZMnAJYBUAa8w5ADtBa5mNETx5aM+yfMj+Qh8yeCuzs7Wrj+qLYgBnYjKfjPBNocLEucaHqP2GBgFZyz/6fu9yi3MrVxjSRzJ93YvD04daeg02vb+RM2FSRxo0bfVXyqu+c1lUftb55y+32lQVXulvcmJJ/UF7QQs1+K+SeYj9Rg+QYo6u+SJSouHW1sR1BXwcFtg5uR646Ljl/KJxM2shjk5BkddeqNhFfOOQQqKhTnKxHJIUdLzzOhX8pOsGBj+I9wZ3gviyA6EB+V5dKI39CKZGRH0pHT+Rkvq8myGTeKNA99b7IHXuj2nyYjvCtETGGWoA0KujVQsEltZFF7oy4F5IFXLEWtwM7ZQSiB1AM/SZdO1S4A49rkH+K7sd4TXt/CzBrhGEeeUjk9heOBJ4gTQ1yfrOvgPAwEusMN7xfQp8vPE6Rowe5ligkdWEIT0D5qSPCqgvF3fku1JTO1vTel9tniL6iXWgGYDVSnpTC8gEsbRR/jdYuP7fYEOXsOSG4s5o=
notifications:
  slack:
    secure: pnzC3U01NxPOZAQt9yznJKdup8ZZdNr6OW3p8dwL9rMfX2pSVrR/YGPc39U4hRiSh0vrI9RJYV2jHnlUjO4+dusyC4MbxGNwaDkheBjcuVPio9jyXwzinLM9QsamGC/v6YIQbS/Dh+hYbBcFEOTnFqGFhEjN2d09/GSQZXHnZaYEeQ1DcC4u8UboFF2mVk1TZxJSEcqHN1WnuvuPgoVi45WUuE3/o6+b/aADc0Z5wE4sCXD3FOdt7QeyKvAgYjFiSSghXME9HKwEqcdyXkuXThG5ThjYwQI800qSBoGYKyMsjs9Pi8Qvg5EZtk0/gBeJRF2Qy82Wz4uLbfRWKiWov6m47SgcFt+gUWaJe5hIcDV/9g18AOPGrdzA5/EEy3+VtBCSD+HX0LjS1Avtp4ccDZwMGK8a2I7Fta2AGXNMP7rhLJy81QMgG0o25yPfwVqWuT7c17jDuxJ2HTReZbrlq0JUbjSG5IYQAy9VHgaQ47+JcQKoLLll8oXPBwS+6LXtmPQBKb2eY5hGFH3cwRSoWc2554YhJelr1dr0mL/xUf7yoyUaCcInbMLaikvE9L1nFs+i1Dcr7rmxnfpV2qasXIprmj4XnRtTD0legLI5M8WZt+LcYGnfYYL/L503nI614BWb8ISSsgFAxQGzwSKAQ9S+ZeSRLeGvoeidycMzjig=
